import type { Metadata } from "next";
import {Balthazar, Noto_Sans} from "next/font/google";
import "@/styles/globals.css"
import Header from "@/components/layout/Header";

const styleFont = Balthazar({
  variable: "--font-style",
  subsets: ["latin"],
  weight:"400"
});

const textFont = Noto_Sans({
  variable: "--font-text",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700"]
});

export const metadata: Metadata = {
  title: "Maha Karya Marker | Dari masa ke masa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${styleFont.variable} ${textFont.variable} font-text antialiased`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
